#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color
token=`cat ~/.finnhubtoken`

while true; do
  clear; date; echo;
  totalc=0
  totalpc=0
  totalb=0

  printf "\e[7m%-6s %-12s %-12s %-12s %-12s %-12s${NC}\n" 'Symbol' 'Current' '%' '$' 'Total %' 'Total $'
  while read t; do
    sym=`echo $t | awk '{print $1}'`
    quantity=`echo $t | awk '{print $2}'`
    base=`echo $t | awk '{print $3}'`
  
    curl -s "https://finnhub.io/api/v1/quote?symbol=$sym&token=$token" >.json
    current=`jq '.c' .json`
    closed=`jq '.pc' .json`
  
    totalb=`echo "scale=2; $quantity*$base+$totalb" | bc -l | awk '{printf "%.2f", $0}'`
    totalc=`echo "scale=2; $quantity*$current+$totalc" | bc -l | awk '{printf "%.2f", $0}'`
    totalpc=`echo "scale=2; $quantity*$closed+$totalpc" | bc -l | awk '{printf "%.2f", $0}'`

    ind=`echo "scale=2; $quantity*($current-$closed)" | bc -l | awk '{printf "%.2f", $0}'`
    chg=`echo "scale=2; 100*($current-$closed)/$closed" | bc -l | awk '{printf "%.2f", $0}'`

    inddiff=`echo "scale=2; $quantity*($current-$base)" | bc -l | awk '{printf "%.2f", $0}'`
    indpct=`echo "scale=2; 100*($current-$base)/$base" | bc -l | awk '{printf "%.2f", $0}'`

    neg=${chg:0:1}
  
    if [ "$neg" = "-" ]; then
      printf "${RED}%-6s %-12s %-12s %-12s${NC}" $sym $current "$chg%" $ind
    else
      printf "${GREEN}%-6s %-12s %-12s %-12s${NC}" $sym $current "+$chg%" "+$ind"
    fi

    neg=${inddiff:0:1}
    if [ "$neg" = "-" ]; then
      printf "${RED} %-12s %-12s${NC}\n" "$indpct%" $inddiff
    else
      printf "${GREEN} %-12s %-12s${NC}\n" "+$indpct%" "+$inddiff"
    fi

  done <~/.tickers
  
  printf "\e[7m%-6s %-12s %-12s %-12s %-12s %-12s${NC}\n" 'Symbol' 'Current' '%' '$' 'Total %' 'Total $'

  # today
  ind=`echo "scale=2; $totalc-$totalpc" | bc -l | awk '{printf "%.2f", $0}'`
  chg=`echo "scale=2; 100*($totalc-$totalpc)/$totalpc" | bc -l | awk '{printf "%.2f", $0}'`
  neg=${chg:0:1}

  if [ "$neg" = "-" ]; then
    printf "${RED}%-6s %-12s %-12s %-12s${NC}\n" 'TODAY' $totalc "$chg%" $ind
  else
    printf "${GREEN}%-6s %-12s %-12s %-12s${NC}\n" 'TODAY' $totalc "+$chg%" "+$ind"
  fi

  # total
  ind=`echo "scale=2; $totalc-$totalb" | bc -l | awk '{printf "%.2f", $0}'`
  chg=`echo "scale=2; 100*($totalc-$totalb)/$totalb" | bc -l | awk '{printf "%.2f", $0}'`
  neg=${chg:0:1}

  if [ "$neg" = "-" ]; then
    printf "${RED}%-6s %-12s %-12s %-12s${NC}\n" 'TODAY' $totalc "$chg%" $ind
  else
    printf "${GREEN}%-6s %-12s %-12s %-12s${NC}\n" 'TOTAL' ' ' "+$chg%" "+$ind"
  fi

  sleep 60
done
